# Assignment 07 - Pandas

In [1]:
import pandas as pd

1) Create a DataFrame from a dictionary with columns Name, Age, City and Salary for 6 employees. Print the first 3 rows, the shape, the column names and the data types.

In [31]:
data = {
    "employee_id":[1,2,3,4,5,6],
    "name": ["Mahad", "Ahad", "Azkia", "Ali", "Ayan", "faizan"],
    "age": [32, 25, 50, 24, 40, 30],
    "city": ["Karachi", "Lahore", "Islamabad", "Delhi", "Delhi", "Karachi"],
    "salary": [30000, 45000, 50000, 35000, 60000, 35000]
}

df = pd.DataFrame(data)
print(df)

   employee_id    name  age       city  salary
0            1   Mahad   32    Karachi   30000
1            2    Ahad   25     Lahore   45000
2            3   Azkia   50  Islamabad   50000
3            4     Ali   24      Delhi   35000
4            5    Ayan   40      Delhi   60000
5            6  faizan   30    Karachi   35000

In [32]:
df.head(3)

   employee_id   name  age       city  salary
0            1  Mahad   32    Karachi   30000
1            2   Ahad   25     Lahore   45000
2            3  Azkia   50  Islamabad   50000

In [33]:
df.shape

(6, 5)

In [34]:
df.columns

Index(['employee_id', 'name', 'age', 'city', 'salary'], dtype='str')

In [35]:
df.dtypes

employee_id    int64
name             str
age            int64
city             str
salary         int64
dtype: object

2) Create a Series of 5 numbers with custom index labels ['a','b','c','d','e']. Print the value at label 'c', the values at positions 1 to 3, and the sum and mean of the Series.

In [36]:
df = pd.Series([100,200,820,480,700],
               index = ['a','b','c','d','e']
)
print(df)

a    100
b    200
c    820
d    480
e    700
dtype: int64

In [37]:
print(df.loc["c"])

820

In [38]:
print(df.iloc[1:4])

b    200
c    820
d    480
dtype: int64

In [39]:
print(df.sum())

2300

In [40]:
print(df.mean())

460.0

3) Create a CSV file (or use any CSV from the class data folder) and read it using pd.read_csv(). Display head(), tail(), info() and describe().

In [41]:
df = pd.read_csv("C:/Users/fisba/Desktop/python online course/module_2_prac/employee_data.csv")
print(df)

   employee_id first_name last_name  department    salary joining_date  age
0            1     Joshua     Ramos  Operations  65313.80   23-05-2024   42
1            2  Christina     Clark          IT  58827.32   02-10-2021   46
2            3   Jonathon  Sullivan  Operations  57427.31   30-04-2020   50
3            4    Clinton   Aguirre          HR  45352.74   04-04-2021   55
4            5   Veronica     Weber  Operations  78772.56   06-10-2020   51
5            6      Louis    Rivera     Finance  30448.72   05-05-2020   41
6            7    Sabrina  Gonzalez   Marketing  88476.72   15-10-2020   48
7            8    Jillian     Lewis   Marketing  49895.55   08-06-2021   33
8            9   Caroline   Kennedy     Finance  88878.64   17-07-2024   47

In [42]:
df.head()

   employee_id first_name last_name  department    salary joining_date  age
0            1     Joshua     Ramos  Operations  65313.80   23-05-2024   42
1            2  Christina     Clark          IT  58827.32   02-10-2021   46
2            3   Jonathon  Sullivan  Operations  57427.31   30-04-2020   50
3            4    Clinton   Aguirre          HR  45352.74   04-04-2021   55
4            5   Veronica     Weber  Operations  78772.56   06-10-2020   51

In [43]:
df.tail()

   employee_id first_name last_name  department    salary joining_date  age
4            5   Veronica     Weber  Operations  78772.56   06-10-2020   51
5            6      Louis    Rivera     Finance  30448.72   05-05-2020   41
6            7    Sabrina  Gonzalez   Marketing  88476.72   15-10-2020   48
7            8    Jillian     Lewis   Marketing  49895.55   08-06-2021   33
8            9   Caroline   Kennedy     Finance  88878.64   17-07-2024   47

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   employee_id   9 non-null      int64
 1   first_name    9 non-null      str
 2   last_name     9 non-null      str
 3   department    9 non-null      str
 4   salary        9 non-null      float64
 5   joining_date  9 non-null      str
 6   age           9 non-null      int64
dtypes: float64(1), int64(2), str(4)
memory usage: 636.0 bytes

In [45]:
df.describe()

       employee_id        salary        age
count     9.000000      9.000000   9.000000
mean      5.000000  62599.262222  45.888889
std       2.738613  19882.950076   6.489307
min       1.000000  30448.720000  33.000000
25%       3.000000  49895.550000  42.000000
50%       5.000000  58827.320000  47.000000
75%       7.000000  78772.560000  50.000000
max       9.000000  88878.640000  55.000000

4) From the DataFrame of Q1, select (a) only the Name and Salary columns, (b) rows where Age is greater than 30, (c) rows where City is 'Delhi' and Salary is above 40000.

In [46]:
df = pd.DataFrame(data)
print(df)

   employee_id    name  age       city  salary
0            1   Mahad   32    Karachi   30000
1            2    Ahad   25     Lahore   45000
2            3   Azkia   50  Islamabad   50000
3            4     Ali   24      Delhi   35000
4            5    Ayan   40      Delhi   60000
5            6  faizan   30    Karachi   35000

In [74]:
print(df[["name","salary"]])

     name  salary
0   Mahad   30000
1    Ahad   45000
2   Azkia   50000
3     Ali   35000
4    Ayan   60000
5  faizan   35000

In [81]:
print(df[df["age"] > 30][["name","age"]])

    name  age
0  Mahad   32
2  Azkia   50
4   Ayan   40

In [97]:
print(df[(df["city"] == "Delhi") & (df["salary"] > 40000)])

   employee_id  name  age   city  salary
4            5  Ayan   40  Delhi   60000

5) Use loc and iloc to (a) get the 2nd row, (b) get Name of the 4th employee, (c) get rows 1 to 3 with columns Name and City.

In [102]:
print(df)

   employee_id    name  age       city  salary
0            1   Mahad   32    Karachi   30000
1            2    Ahad   25     Lahore   45000
2            3   Azkia   50  Islamabad   50000
3            4     Ali   24      Delhi   35000
4            5    Ayan   40      Delhi   60000
5            6  faizan   30    Karachi   35000

In [106]:
df.loc[1]

employee_id         2
name             Ahad
age                25
city           Lahore
salary          45000
Name: 1, dtype: object

In [109]:
df.loc[3,"name"]

'Ali'

In [111]:
print(df.loc[1:3, ["name", "city"]])

    name       city
1   Ahad     Lahore
2  Azkia  Islamabad
3    Ali      Delhi

6) Add a new column 'Bonus' that is 10% of Salary and a column 'Total' = Salary + Bonus. Then rename the column 'City' to 'Location' and drop the 'Bonus' column.

In [137]:

df["Bonus"] = df["salary"] * 0.10
df["Total"] = df["salary"] + df["Bonus"]

print(df[["salary", "Bonus", "Total"]])

   salary   Bonus    Total
0   30000  3000.0  33000.0
1   45000  4500.0  49500.0
2   50000  5000.0  55000.0
3   35000  3500.0  38500.0
4   60000  6000.0  66000.0
5   35000  3500.0  38500.0

In [138]:
df = df.rename(columns={
    "city":"location"
})
print(df)

   employee_id    name  age   location  salary    Total   Bonus
0            1   Mahad   32    Karachi   30000  33000.0  3000.0
1            2    Ahad   25     Lahore   45000  49500.0  4500.0
2            3   Azkia   50  Islamabad   50000  55000.0  5000.0
3            4     Ali   24      Delhi   35000  38500.0  3500.0
4            5    Ayan   40      Delhi   60000  66000.0  6000.0
5            6  faizan   30    Karachi   35000  38500.0  3500.0

In [ ]:
df = df.drop(columns="Bonus")
df

   employee_id    name  age   location  salary    Total
0            1   Mahad   32    Karachi   30000  33000.0
1            2    Ahad   25     Lahore   45000  49500.0
2            3   Azkia   50  Islamabad   50000  55000.0
3            4     Ali   24      Delhi   35000  38500.0
4            5    Ayan   40      Delhi   60000  66000.0
5            6  faizan   30    Karachi   35000  38500.0

7) Create a DataFrame having some missing values (NaN). Find the count of missing values in each column, fill numeric NaNs with the column mean, and drop rows that still have missing values.

In [155]:
data = {
    "Name": ["Mahad", "Ahad", "Azkia", "Ali", "Mustafa"],
    "Age": [20, None, 25, 22, None],
    "Salary": [30000, 45000, None, 35000, 50000],
    "City": ["Karachi", "Lahore", None, "Delhi", "Islamabad"]
}

df = pd.DataFrame(data)
print(df)

      Name   Age   Salary       City
0    Mahad  20.0  30000.0    Karachi
1     Ahad   NaN  45000.0     Lahore
2    Azkia  25.0      NaN        NaN
3      Ali  22.0  35000.0      Delhi
4  Mustafa   NaN  50000.0  Islamabad

In [161]:
df.isnull().sum()

Name      0
Age       2
Salary    1
City      1
dtype: int64

In [170]:
df["Salary"].mean()

np.float64(40000.0)

In [171]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [177]:
df = df.dropna()

In [178]:
print(df)

    Name   Age   Salary     City
0  Mahad  20.0  30000.0  Karachi
3    Ali  22.0  35000.0    Delhi

8) Sort the DataFrame by Salary in descending order, and then by Age in ascending order. Also print the top 3 highest-paid employees using nlargest().

In [180]:
df = pd.read_csv("C:/Users/fisba/Desktop/python online course/module_2_prac/employee_data.csv")
df

   employee_id first_name last_name  department    salary joining_date  age
0            1     Joshua     Ramos  Operations  65313.80   23-05-2024   42
1            2  Christina     Clark          IT  58827.32   02-10-2021   46
2            3   Jonathon  Sullivan  Operations  57427.31   30-04-2020   50
3            4    Clinton   Aguirre          HR  45352.74   04-04-2021   55
4            5   Veronica     Weber  Operations  78772.56   06-10-2020   51
5            6      Louis    Rivera     Finance  30448.72   05-05-2020   41
6            7    Sabrina  Gonzalez   Marketing  88476.72   15-10-2020   48
7            8    Jillian     Lewis   Marketing  49895.55   08-06-2021   33
8            9   Caroline   Kennedy     Finance  88878.64   17-07-2024   47

In [182]:
df.sort_values(by="salary", ascending=False)

   employee_id first_name last_name  department    salary joining_date  age
8            9   Caroline   Kennedy     Finance  88878.64   17-07-2024   47
6            7    Sabrina  Gonzalez   Marketing  88476.72   15-10-2020   48
4            5   Veronica     Weber  Operations  78772.56   06-10-2020   51
0            1     Joshua     Ramos  Operations  65313.80   23-05-2024   42
1            2  Christina     Clark          IT  58827.32   02-10-2021   46
2            3   Jonathon  Sullivan  Operations  57427.31   30-04-2020   50
7            8    Jillian     Lewis   Marketing  49895.55   08-06-2021   33
3            4    Clinton   Aguirre          HR  45352.74   04-04-2021   55
5            6      Louis    Rivera     Finance  30448.72   05-05-2020   41

In [183]:
df.sort_values(by="age", ascending=True)

   employee_id first_name last_name  department    salary joining_date  age
7            8    Jillian     Lewis   Marketing  49895.55   08-06-2021   33
5            6      Louis    Rivera     Finance  30448.72   05-05-2020   41
0            1     Joshua     Ramos  Operations  65313.80   23-05-2024   42
1            2  Christina     Clark          IT  58827.32   02-10-2021   46
8            9   Caroline   Kennedy     Finance  88878.64   17-07-2024   47
6            7    Sabrina  Gonzalez   Marketing  88476.72   15-10-2020   48
2            3   Jonathon  Sullivan  Operations  57427.31   30-04-2020   50
4            5   Veronica     Weber  Operations  78772.56   06-10-2020   51
3            4    Clinton   Aguirre          HR  45352.74   04-04-2021   55

In [186]:
df.nlargest(3,"salary")

   employee_id first_name last_name  department    salary joining_date  age
8            9   Caroline   Kennedy     Finance  88878.64   17-07-2024   47
6            7    Sabrina  Gonzalez   Marketing  88476.72   15-10-2020   48
4            5   Veronica     Weber  Operations  78772.56   06-10-2020   51

9) Using groupby, find the average salary per City, the number of employees per City, and the maximum salary per City. Show the result using agg() with multiple functions.

In [187]:
data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "First_Name": ["Mahad", "Affan", "Sarim", "Ahad","Mustafa", "Ali", "Rehan", "Azkia"],
    "Last_Name": ["Farman", "Khan", "Ahmed", "Ali","Raza", "Malik", "Ahmed", "Rauf"],
    "Department": ["Sales", "IT", "HR", "IT","Sales", "HR", "IT", "Sales"],
    "Salary": [85000, 65000, 62000, 78000,70000, 65000, 95000, 80000],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad","Lahore", "Karachi", "Islamabad", "Lahore"]
}

df = pd.DataFrame(data)
df

   Employee_ID First_Name Last_Name Department  Salary       City
0          101      Mahad    Farman      Sales   85000    Karachi
1          102      Affan      Khan         IT   65000     Lahore
2          103      Sarim     Ahmed         HR   62000    Karachi
3          104       Ahad       Ali         IT   78000  Islamabad
4          105    Mustafa      Raza      Sales   70000     Lahore
5          106        Ali     Malik         HR   65000    Karachi
6          107      Rehan     Ahmed         IT   95000  Islamabad
7          108      Azkia      Rauf      Sales   80000     Lahore

In [189]:
# Group by City and apply multiple functions

Analysis = df.groupby("City").agg(
    Avg_Salary=("Salary", "mean"),
    No_of_Employees=("Employee_ID", "count"),
    Max_Salary=("Salary", "max")
)
Analysis

             Avg_Salary  No_of_Employees  Max_Salary
City
Islamabad  86500.000000                2       95000
Karachi    70666.666667                3       85000
Lahore     71666.666667                3       80000

10) Create two DataFrames (employees and departments) with a common column 'DeptID'. Merge them using inner and left joins, then concatenate two DataFrames of the same structure using pd.concat() and remove duplicate rows.

In [193]:
employees = pd.DataFrame({
    "id":         [1, 2, 3, 4],
    "name":       ["Mahad", "Affan", "Ahad", "Ali"],
    "dept_id":    [10, 20, 10, 30]
})

departments = pd.DataFrame({
    "dept_id":   [10, 20, 40],
    "dept_name": ["Engineering", "Finance", "Marketing"]
})
print(employees)
print(departments)

   id   name  dept_id
0   1  Mahad       10
1   2  Affan       20
2   3   Ahad       10
3   4    Ali       30
   dept_id    dept_name
0       10  Engineering
1       20      Finance
2       40    Marketing

In [197]:
inner = pd.merge(employees, departments, on="dept_id", how="inner")
inner

   id   name  dept_id    dept_name
0   1  Mahad       10  Engineering
1   2  Affan       20      Finance
2   3   Ahad       10  Engineering

In [196]:
left = pd.merge(employees, departments, on="dept_id", how="left")
left

   id   name  dept_id    dept_name
0   1  Mahad       10  Engineering
1   2  Affan       20      Finance
2   3   Ahad       10  Engineering
3   4    Ali       30          NaN

In [204]:
combined = pd.concat([employees, employees], ignore_index=True)
combined = combined.drop_duplicates()

print(combined)

   id   name  dept_id
0   1  Mahad       10
1   2  Affan       20
2   3   Ahad       10
3   4    Ali       30